import { media } from './media';

export type Competition = {
  slug: string;
  audience: 'GURU' | 'MURID';
  officialName: string;
  tagline: string;
  status: string;
  phase: 'PRA_ACARA' | 'PENILAIAN' | 'KEMUNCAK';
  description: string;
  format: string[];
  journey: string[];
  kemuncak: string;
  heroImages: string[];
};

export const competitions: Competition[] = [
  { slug: 'ci3m', audience: 'GURU', officialName: 'PUICE: Cetusan Inspirasi Tiga Minit (CI3M)', tagline: 'Idea hebat. Tiga minit. Satu pentas.', status: 'Pra-Acara · 19 Ogos', phase: 'PRA_ACARA', description: 'Platform eksklusif untuk guru membentangkan inovasi dan amalan baik dalam Pembelajaran dan Pemudahcaraan (PdPc) secara pantas, padat dan memberi impak melalui pitching tiga minit.', format: ['Pitching tiga minit', 'Sesi penilaian juri', 'Idea terpilih ke Champion Showcase'], journey: ['19 Ogos · Pra-Acara PUICE 2026', 'Pitching tiga minit dan penilaian CI3M', '10 September · Champion Showcase & pengumuman'], kemuncak: 'Idea terpilih kembali ke pentas untuk Champion Showcase di Kemuncak PUICE 2026.', heroImages: [...media.competitions.ci3m] },
  { slug: 'inovasi-guru', audience: 'GURU', officialName: 'PUICE: Inovasi Guru', tagline: 'Inovasi yang mengubah cara kita mengajar dan belajar.', status: 'Pra-Acara · 19 Ogos', phase: 'PRA_ACARA', description: 'Pertandingan ini melahirkan guru inovatif sebagai pemangkin transformasi pendidikan menerusi Pembelajaran Abad Ke-21 (PAK-21) dan pendigitalan. Ia membuka ruang untuk guru berkongsi, mempamerkan dan menyebar luas inovasi PdP yang kreatif serta berdampak tinggi.', format: ['Pameran inovasi', 'Demonstrasi kepada juri', 'Idea terpilih ke Champion Showcase'], journey: ['19 Ogos · Pra-Acara PUICE 2026', 'Demonstrasi inovasi dan penilaian', '10 September · Champion Showcase & pengumuman'], kemuncak: 'Inovasi terpilih diraikan dan dibawa ke hadapan komuniti PUICE di Kemuncak.', heroImages: [...media.competitions['inovasi-guru']] },
  { slug: 'poster-digital', audience: 'GURU', officialName: 'Poster Digital', tagline: 'Idea pendidikan melalui komunikasi visual.', status: 'Dalam Penilaian', phase: 'PENILAIAN', description: 'Pertandingan reka bentuk poster digital 100% dalam talian, tanpa pembentangan lisan. Guru mempamerkan amalan baik dan inovasi PdP melalui kanvas visual yang mampu menyampaikan idea dengan sendiri.', format: ['Penghantaran 100% dalam talian', 'Tiada pembentangan lisan', 'Penilaian visual dan kandungan'], journey: ['Penghantaran poster digital', 'Penilaian reka bentuk dan kandungan', '10 September · Keputusan diumumkan'], kemuncak: 'Keputusan akan diumumkan di Kemuncak PUICE 2026.', heroImages: [...media.competitions['poster-digital']] },
  { slug: 'kajian-tindakan', audience: 'GURU', officialName: 'Pembentangan Kajian Tindakan', tagline: 'Penyelidikan yang mencetus refleksi dan penambahbaikan.', status: 'Menuju Kemuncak', phase: 'KEMUNCAK', description: 'Kajian Tindakan ialah penyelidikan berasaskan amalan kendiri guru: mengenal pasti isu PdP, merancang intervensi, melaksanakan strategi baharu dan menilai keberkesanannya untuk meningkatkan pengajaran serta pencapaian murid.', format: ['Pembentangan dapatan', 'Perkongsian intervensi PdP', 'Soal jawab bersama juri'], journey: ['Pengenalpastian isu dan intervensi PdP', 'Pembentangan Kajian Tindakan', '10 September · Keputusan diumumkan'], kemuncak: 'Dapatan dan usaha penambahbaikan diraikan sebagai sebahagian daripada perjalanan PUICE 2026.', heroImages: [...media.competitions['kajian-tindakan']] },
  { slug: 'kmr', audience: 'MURID', officialName: 'Kefahaman Melalui Reka Bentuk (KmR)', tagline: 'Pembelajaran bermakna melalui reka bentuk bertujuan.', status: '10 September', phase: 'KEMUNCAK', description: 'KmR atau Understanding by Design (UbD) menggunakan pendekatan reka bentuk dari belakang: menetapkan hasil pembelajaran, menentukan bukti kefahaman, kemudian merancang aktiviti. Ia menggabungkan mata pelajaran di bawah satu Idea Utama bagi menyelesaikan masalah atau menghasilkan produk.', format: ['Idea Utama rentas mata pelajaran', 'Bukti kefahaman', 'Produk dan pembentangan'], journey: ['Hasil pembelajaran dan Idea Utama dikenal pasti', 'Bukti kefahaman serta aktiviti pembelajaran direka bentuk', '10 September · Pertandingan di Kemuncak'], kemuncak: 'Pertandingan KmR berlangsung di Kemuncak PUICE 2026.', heroImages: [...media.competitions.kmr] },
  { slug: 'pbl', audience: 'MURID', officialName: 'Pembelajaran Berasaskan Projek (PBL)', tagline: 'Belajar dengan mencipta penyelesaian sebenar.', status: '10 September', phase: 'KEMUNCAK', description: 'PBL ialah pembelajaran interaktif yang membawa murid daripada teori kepada proses mereka cipta dan menyelesaikan masalah sebenar. Pasukan membangunkan produk, prototaip atau model inovasi, menyediakan folio dan membentangkannya kepada juri.', format: ['Produk, prototaip atau model', 'Laporan atau folio', 'Pembentangan kepada juri'], journey: ['Isu dunia sebenar dikenal pasti', 'Produk, prototaip atau model dibangunkan', '10 September · Pembentangan kepada juri'], kemuncak: 'Pasukan PBL membentangkan penyelesaian mereka secara langsung di Kemuncak PUICE 2026.', heroImages: [...media.competitions.pbl] },
  { slug: 'pbl-stem', audience: 'MURID', officialName: 'Pembelajaran Berasaskan Projek STEM (PBL-STEM)', tagline: 'STEM dan kreativiti untuk masalah dunia sebenar.', status: '10 September', phase: 'KEMUNCAK', description: 'Pertandingan ini menilai keupayaan murid menghasilkan projek berasaskan pembelajaran berasaskan projek yang mengintegrasikan Sains, Teknologi, Kejuruteraan dan Matematik (STEM) untuk menyelesaikan masalah kehidupan sebenar.', format: ['Integrasi Sains, Teknologi, Kejuruteraan dan Matematik', 'Prototaip atau model', 'Demonstrasi dan pembentangan'], journey: ['Masalah kehidupan sebenar dikenal pasti', 'Projek bersepadu STEM dibangunkan', '10 September · Penilaian di Kemuncak'], kemuncak: 'Projek PBL-STEM dipersembahkan dan dinilai di Kemuncak PUICE 2026.', heroImages: [...media.competitions['pbl-stem']] },
];

export function getCompetition(slug: string) {
  return competitions.find((competition) => competition.slug === slug);
}
